### PR TITLE
merging with interactive_marker

### PR DESCRIPTION
**Pull request by mklingen**
Merges or_interactivemarker with or_rviz to make one new viewer.

* Uses or_interactivemarker classes for rendering and interacting with kinbodies and plots
* Uses or_rviz code for creating the window, controlling the background color, controlling the camera, lighting, and switching between environments
* Old or_rviz rendering and plotting code is still around but commented out or not used.

### CODE REVIEW

**Comment by psigen** [comment]
Looks good.  Can we strip out any unused code?  I didn't actually see much of it, just a few commented commands that no longer exist.

It seems like if we are going through the trouble of making a formal pull request and reviewing the code, this is the best possible time to strip out old unused code.

Plus, if we need to refer to the older code, we can easily revert to the pre-pull-request version.

**Comment by mkoval** [comment]
Two comments:
1. We should register both the `or_rviz` and `or_interactivemarker` viewers. It's still useful to use `or_interactivemarker` to connect to an external RViz instance (e.g. when frequently restarting OpenRAVE). This is just a matter of adding an extra case to `CreatePluginValidated` and `GetPluginAttributesValidated`.
2. I'd like to import `or_interactivemarker` into `or_rviz` in a way that preserves history (i.e. subtree merge). This comes in handy for debugging.

**Comment by mklingen** [comment]
@mkoval, 

1. would be tricky with this setup but not impossible. Something would need to spin up the marker server without creating an RVIZ instance. Would require taking out a lot of the stuff and putting it into a library, then referencing the library in two separate viewers.

2. I don't think this is possible. The files are in totally separate repositories. Would potentially be possible if instead of modifying `or_rviz` to include `or_interactivemarker` I do it the other way around -- but then you lose the history on `or_rviz`.

**Comment by mklingen** [comment]
Merging in anyway, as I don't see any benefit to keeping `or_rviz` the way it was before.

**Pull request merged**
