### PR TITLE
Added a README

### PR DESCRIPTION
**Pull request by mkoval**
I took a stab at fleshing out the README as part of our larger documentation effort.

@mklingen @psigen Anything else we should add here?

### CODE REVIEW

**Comment by mkoval** [comment]
@aaronjoh Can you take a look?

**Comment by aaronjoh** [comment]
The out-of-process viewer example needs a little more detail. Running this:

```
import openravepy
env = openravepy.Environment()
env.SetViewer('InteractiveMarker')
```

as suggested by the readme, and then separately running:

```
rosrun rviz rviz
```

does not work and puts out this error:

```
[ERROR] [1423682423.086219712]: PluginlibFactory: The plugin for class 'or_interactivemarker::rviz::EnvironmentDisplay' failed to load.  Error: Could not find library corresponding to plugin or_interactivemarker::rviz::EnvironmentDisplay. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```

I'm sure this is just me missing a step, but I'm working only from the Readme.md. In-process viewer launches, though for both a suggested action or test that actually does something would be nice.

It would similarly be nice to have scripts/test.py either be the same as what is indicated in the readme, or have the readme setup how to run the test script.

**Comment by mkoval** [comment]
@aaronjoh I made some changes to address your comments. Can you take another look?

**Comment by aaronjoh** [comment]
Ok, looks good. Might add a note that the scripts/test.py is a good place to start (though that pulls the model from /opt/pr so i guess we might drop that from the release?)

**Comment by mkoval** [comment]
I updated the `test.py` script and now mention it in `README`.

**Pull request merged**
